name: Deploy to EC2

on:
  push:
    branches: [main] # Triggers when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Navigate to your project directory
            cd /home/ubuntu/boardd-backend

            # Pull latest changes
            git pull origin main

            # Install/update dependencies
            npm install --production

            # Restart PM2
            pm2 restart backend

            # Show status to confirm deployment
            pm2 status

            echo "🚀 Deployment completed successfully!"
